### PR TITLE
json hype

### PR DESCRIPTION
**Pull request by omkelderman**
I added an option to create a "json-output build".
Enable the `OUTPUT_AS_JSON` option in the makefile (and make sure to disable verbose as it says :stuck_out_tongue:) and it should be gud to go :smile:

Basically what it does is it disables all the `printf`s and `puts`s (so yes, including the fancy start :cry:) and adds one fancy thing that outputs some json-string. (https://github.com/nlohmann/json is pretty awesome apparently :smiley:)

As for use-case? can come in handy when you want to parse the output. Json was the first thing that came to my mind. :stuck_out_tongue_winking_eye: 

I noticed there was a "windows makefile" and other windows-specific stuff. I havent touched that so its probably horribly broken on windows. I cant build the current version on windows anyway, my visual studio spams me a whole bunch of compiler-errors about stuff not being in the `std` namespace (`min` and `max` for example i think, cant remember exactly)

### CODE REVIEW

**Comment by omkelderman** [comment]
update: I put the changes I made to the "normal" makefile in the "windows" makefile so they are more or less back in sync now :smile: so that should be gud, altho I still get compilor-errors when building the thing on windows, this time I tried mingw (updated to the newest gcc avaiable on there) so not sure whats going on there....

But if you where able to make a windows-build with the previous "windows makefile" you should be able to make one with this one

**Comment by Francesco149** [comment]
hey, thanks for the pull request! I will check it out asap

**Comment by magicnat** [comment]
oh 10,032 lines added 🌚
try git's `submodule` instead?

**Comment by Francesco149** [comment]
erm, sorry but this json module is a bit too template heavy for oppai. I don't want to slow compile times down, in fact I was going to work on making oppai into a single translation unit to make it as quick to build as possible, without depending on any 3rd party libraries. I will add a link to your fork to the readme though.

**Comment by omkelderman** [comment]
Hehe, I understand :p

I literally threw this together in one evening of trial and error.

My main goal is having something thats easy parsable my another process, if
that means ditching json and going for something else, I completely don't
mind. Heck I could even just literally write the json itself if im gonna
stick with json, its not even that hard xd.

Maybe wait a bit with that link in the readme, maybe I can think of
something that better suits your requirements :p

**Comment by Francesco149** [comment]
well, since it's just json output you don't need a full json library for this. you can easily just printf format the output into json and that's it. no need for pretty printing on anything, since it's going to be parsed and trimmed anyways.

**Comment by omkelderman** [comment]
> Heck I could even just literally write the json itself if im gonna
> stick with json, its not even that hard xd.

as in, this :P

also im open to other suggestions beside json, as long as its easy (and preferably language independen, so everyone can use it) to parse i dont care :P

**Comment by omkelderman** [comment]
~~oh lol, lots of end-of-line spaces where removed my atom xd, oh well (want me to revert those for cleaner diff?)~~ (edit: did it anyway, I had some WIP-comments in there I had to remove anyway :stuck_out_tongue:)

**anyways, json.hpp is now gone :smile:**

The resulting json-printf should be pretty manageable. I tried putting things on one line that sort of make sense (I more or less copied over bits from your `printf`s :wink:)

**Comment by thehowl** [comment]
But what about songs with " in them? :P I'd say to replace in all the strings " with \", so that it becomes correct JSON.

On 29 June 2016 18:18:53 CEST, Olle Kelderman notifications@github.com wrote:

> oh lol, lots of end-of-line spaces where removed my atom xd, oh well
> (want me to revert those for cleaner diff?)
> 
> **anyways, json.hpp is now gone :smile:**
> 
> The resulting json-printf should be pretty manageable. I tried putting
> things on one line that sort of make sense (I more or less copied over
> bits from your `printf`s :wink:)
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Francesco149/oppai/pull/7#issuecomment-229408631

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by omkelderman** [comment]
oh jesus, thanks for pointing that out, completely forgot about that.. crap, brb crying and fixin shit

**Comment by omkelderman** [comment]
ok done, i opted for a `printStrAsJson` instead of some `parseToJson` thing, so I dont have to allocate new strings, since the string would grow in size. It doesn't matter anyway that the string being printed gets invalidated by `strtok` since the program literally ends right after that.

Downside is that my fancy `printf` doesnt look that fancy anymore, oh well

**Comment by Francesco149** [comment]
ok, gonna merge this.

a few things I have fixed:
- json strings must also escape '\' so I rewrote your escaping function
- moved around some ifdefs
- renamed the json string func to match my coding style

**Comment by Francesco149** [comment]
**accepted and merged.** 

sorry for the late reply, I am not very consistent at working on projects :P

also, I squashed the commits together and it seems that github doesn't want to mark this as merged unless it find the same exact commits in the master branch :/ so I can't mark this as merged even though it is.

thanks for the help!

**Comment by omkelderman** [comment]
:+1:
Also props for rewriting the print json string function! I like it :smile: (bonus: no more ugly non-const parameter :stuck_out_tongue:)

_edit:_

> sorry for the late reply, I am not very consistent at working on projects :P

dont worry about it ^^ im pretty much the same xd

**Comment by Francesco149** [comment]
just made output mode somewhat modular

you can now use the -o parameter to select json output by specifying -ojson

I will eventually bring this one step further and implement standard json rpc error codes instead of not outputting json on errors.

**Comment by omkelderman** [comment]
or what could be cool is using a non-zero exit code on error, so when you run it you know you shouldnt put it in a json-parser when exit-code is non-zero

**Pull request closed without merging**
